### ISSUE TITLE
Sharejs op error on opening new projects

### ISSUE THREAD

**Issue by joelmoss** [codio/Issues#2]
This happens on creating projects with a name that existed at some point in the past.

![screen shot 2014-02-18 at 15 44 57](https://f.cloud.github.com/assets/4614/2196902/cc498d7e-98b5-11e3-9161-e8b7cfa0631c.png)

**Comment by dignifiedquire** [comment]
See share/livedb#16 which is probably the reason for this.

**Comment by joelmoss** [comment]
You able to fix? Got an ETA?

**Comment by dignifiedquire** [comment]
Well as I told @fmay in Flowdock I was able to fix a single project by hand and I know that the reason is that somehow there is a wrong entry in the redis collection `codio_ops` which results in this error. I think I'll be able to fix this tomorrow but that depends on how deeply nested that issues is in livedb or in our code.

**Comment by joelmoss** [comment]
Closed in favour of codio/client#2406
